services:
  frontend:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_BASEURL=${VITE_BASEURL}
      - VITE_APIKEY=${VITE_APIKEY}
      - VITE_AUTHDOMAIN=${VITE_AUTHDOMAIN}
      - VITE_PROJECTID=${VITE_PROJECTID}
      - VITE_STORAGEBUCKET=${VITE_STORAGEBUCKET}
      - VITE_MESSAGINGSENDERID=${VITE_MESSAGINGSENDERID}
      - VITE_APPID=${VITE_APPID}
      - VITE_GOOGLE_MAPS_API_KEY=${VITE_GOOGLE_MAPS_API_KEY}

    # restart: unless-stopped
