name: "build and deploy docker image"
on:
  push:
    # tags:
    #   - "*" # Trigger เมื่อ push tag ใด ๆ
    branches:
      - test-prod

jobs:
  release-docker-image-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2

      # - name: Set TAG_NAME from Git tag
      #   run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker Image
        run: docker build -t ghcr.io/patiphatrattanosot/visit-home-frontend:latest -f ./Dockerfile.prod .

      - name: Push Docker images to GHCR
        run: |
          docker push ghcr.io/patiphatrattanosot/visit-home-frontend:latest

  auto-deploy-docker-job:
    needs: release-docker-image-job
    runs-on: ubuntu-latest
    steps:
      - name: Extract tag name again (ensure env variable is set)
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy via SSH with Password
        run: |
          sshpass -p '${{ secrets.SSH_DIGITALOCEAN }}' ssh -o StrictHostKeyChecking=no root@206.189.92.255 << 'EOF'
            docker logout ghcr.io
            echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u patiphatrattanosot --password-stdin

            # ลบ container เก่า
            docker rm -f visit-home-frontend || true

            # สร้าง network 
            # docker network create visit-home-network || true

            # เอา image ไปที่ server
            docker pull ghcr.io/patiphatrattanosot/visit-home-frontend:latest
            
            # สั่งให้รัน container ใหม่ และ map environment 
            docker run --restart=always -d --pull always \
            -e VITE_BASEURL=${{secrets.VITE_BASEURL}} \
            -e VITE_APIKEY="${{secrets.VITE_APIKEY}}" \
            -e VITE_AUTHDOMAIN=${{secrets.VITE_AUTHDOMAIN}} \
            -e VITE_PROJECTID=${{secrets.VITE_PROJECTID}} \
            -e VITE_STORAGEBUCKET=${{secrets.VITE_STORAGEBUCKET}} \
            -e VITE_MESSAGINGSENDERID=${{secrets.VITE_MESSAGINGSENDERID}} \
            -e VITE_APPID=${{secrets.VITE_APPID}} \
            -e VITE_GOOGLE_MAPS_API_KEY=${{secrets.VITE_GOOGLE_MAPS_API_KEY}} \
            --name visit-home-frontend \
            -p 80:5173 \
            --network visit-home-network \
            ghcr.io/patiphatrattanosot/visit-home-frontend:latest
          EOF
