name: "build and deploy docker image"
on:
  push:
    branches:
      - test-prod

jobs:
  release-docker-image-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker Image with Build Args
        run: |
          docker build \
            --build-arg VITE_BASEURL="${{ secrets.VITE_BASEURL }}" \
            --build-arg VITE_APIKEY="${{ secrets.VITE_APIKEY }}" \
            --build-arg VITE_AUTHDOMAIN="${{ secrets.VITE_AUTHDOMAIN }}" \
            --build-arg VITE_PROJECTID="${{ secrets.VITE_PROJECTID }}" \
            --build-arg VITE_STORAGEBUCKET="${{ secrets.VITE_STORAGEBUCKET }}" \
            --build-arg VITE_MESSAGINGSENDERID="${{ secrets.VITE_MESSAGINGSENDERID }}" \
            --build-arg VITE_APPID="${{ secrets.VITE_APPID }}" \
            --build-arg VITE_GOOGLE_MAPS_API_KEY="${{ secrets.VITE_GOOGLE_MAPS_API_KEY }}" \
            -t ghcr.io/patiphatrattanosot/visit-home-frontend:latest \
            -f ./Dockerfile.prod .

      - name: Push Docker images to GHCR
        run: |
          docker push ghcr.io/patiphatrattanosot/visit-home-frontend:latest

  auto-deploy-docker-job:
    needs: release-docker-image-job
    runs-on: ubuntu-latest
    steps:
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy via SSH with Password
        run: |
          sshpass -p '${{ secrets.SSH_DIGITALOCEAN }}' ssh -o StrictHostKeyChecking=no root@206.189.92.255 << 'EOF'
            docker logout ghcr.io
            echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u patiphatrattanosot --password-stdin

            # ลบ container เก่า
            docker rm -f visit-home-frontend || true

            # เอา image ใหม่
            docker pull ghcr.io/patiphatrattanosot/visit-home-frontend:latest

            echo "Deploying visit-home-frontend..."

            # รัน container ใหม่ (ไม่ต้องใส่ -e เพราะ env vars ฝังใน image แล้ว)
            docker run --restart=always -d \
            --name visit-home-frontend \
            -p 80:80 \
            --network visit-home-network \
            ghcr.io/patiphatrattanosot/visit-home-frontend:latest

            echo "Frontend deployed successfully!"
          EOF